try:
	from tkinter import *
	from tkinter.scrolledtext import ScrolledText
	def main():
		exec("from freegames import "+game.get())
	top=Tk()
	top.title("小游戏")
	top.geometry('1500x20')
	Label(text='请输入游戏菜单中的游戏：').pack(side=LEFT)
	c=ScrolledText()
	game=Entry()
	game.pack(side=LEFT,expand=True,fill=X)
	Label(text='游戏菜单：ant').pack(side=LEFT)
	Label(text='bagels').pack(side=LEFT)
	Label(text='bounce').pack(side=LEFT)
	Label(text='cannon').pack(side=LEFT)
	Label(text='connect').pack(side=LEFT)
	Label(text='crypto').pack(side=LEFT)
	Label(text='fidget').pack(side=LEFT)
	Label(text='flappy').pack(side=LEFT)
	Label(text='guess').pack(side=LEFT)
	Label(text='life').pack(side=LEFT)
	Label(text='maze').pack(side=LEFT)
	Label(text='memory').pack(side=LEFT)
	Label(text='minesweeper').pack(side=LEFT)
	Label(text='pacman').pack(side=LEFT)
	Label(text='paint').pack(side=LEFT)
	Label(text='pong').pack(side=LEFT)
	Label(text='simonsays').pack(side=LEFT)
	Label(text='snake').pack(side=LEFT)
	Label(text='tictactoe').pack(side=LEFT)
	Label(text='tiles').pack(side=LEFT)
	Label(text='trons').pack(side=LEFT)
	Button(text='玩',command=main).pack(side=RIGHT)
	mainloop()
except Exception as e:
	print(e)
